runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app -t 120

runtime_config:
  python_version: 3

resources:
  cpu: 2
  memory_gb: 4

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.9

#readiness_check:
#  app_start_timeout_sec: 600

#health_check:
#  enable_health_check: False