runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

resources:
  cpu: 8
  memory_gb: 2

#readiness_check:
#  app_start_timeout_sec: 600

#health_check:
#  enable_health_check: False